import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/Themeprovider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        data-new-gr-c-s-check-loaded="14.1228.0"
        data-gr-ext-installed=""
        className="vsc-initialized"
      >
        <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
